bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost port=5432 user=admin password=root dbname=db sslmode=disable"
session_key = "6g475hg5l4f76f745hg7lh54g7jg7hl4f7lh45fyy6f764f76f45f7y45fytdrys97gu976y0ifs13f24"